#require: rubocop-rspec

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.0.1

  # additional excludes for Rails
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'log'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 15

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 30

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false
