# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/response.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/common/response.proto", :syntax => :proto3) do
    add_message "Response" do
    end
  end
end

Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Response").msgclass
