# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/occupations/occupations2.proto

require 'google/protobuf'

require 'proto/common/response_pb'
require 'google/protobuf/wrappers_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/occupations/occupations2.proto", :syntax => :proto3) do
    add_message "Occupation.Occupations" do
      repeated :occupations, :message, 1, "Occupation.Occupation"
    end
    add_message "Occupation.Occupation" do
      optional :is_for_saudi_only, :string, 2
      optional :is_valid_for_istiqdam, :string, 3
      optional :qsim_code, :string, 4
      optional :jza_code, :string, 5
      optional :bab_code, :string, 6
      optional :fsl_code, :string, 7
      optional :mhn_code, :string, 8
      optional :mst_code, :string, 9
      optional :can_change_online, :string, 10
      optional :created_on, :string, 11
      optional :modified_on, :string, 12
      optional :is_wp_required, :string, 13
      optional :is_gov_support_ewv, :string, 14
      optional :is_engineering_job, :string, 15
      optional :is_valid_for_istiqdam1_5, :string, 16
      optional :is_home_job, :string, 17
      optional :is_medical_job, :string, 18
      optional :nic_code, :string, 19
      optional :is_accountant_job, :string, 20
      optional :is_allowed_for_monshaat_visa, :string, 21
      optional :is_blocked_for_seasonal_visas, :string, 22
      optional :nic_old_code, :string, 23
      optional :job_group_id, :string, 24
      optional :is_gender_required, :string, 25
      optional :saudization_management, :string, 26
      optional :saudization_action_type, :string, 27
      optional :minimum_wage, :string, 28
    end
  end
end

module Occupation
  Occupations = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Occupation.Occupations").msgclass
  Occupation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Occupation.Occupation").msgclass
end
