# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: proto/occupations/occupations2.proto for package 'Occupation'

require "grpc"
require "proto/occupations/occupations2_pb"

module Occupation
  module Router
    # Service created for routing to modules based on event bindings or by another words it's interface
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "Occupation.Router"

      rpc :EventProtoSend, ::Occupation::Occupations, ::Response
      rpc :EventProtoSendd, ::Occupation::Occupations, ::Response
    end

    Stub = Service.rpc_stub_class
  end
end
